# Generated by Django 4.2.5 on 2023-09-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('enquiry', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/inventory/')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('availability', models.CharField(choices=[('Y', 'Available'), ('N', 'Sold')], max_length=50)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('ImagesID', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
