# Generated by Django 4.2.5 on 2023-09-28 18:25

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('enquiry', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=500)),
                ('image', models.URLField(max_length=500)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('SUV', 'SUV'), ('Trailer', 'Trailer'), ('Classic', 'Classic'), ('Other', 'Other')], max_length=50)),
                ('availability', models.CharField(choices=[('In-stock', 'Available'), ('No-stock', 'Sold')], max_length=50)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('video', models.FileField(blank=True, null=True, upload_to='video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['', 'MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('date_uploaded', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, default='images/inventory/default.jpg', null=True, upload_to='images/inventory/')),
                ('filename', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_fk', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_fk', to='frontapp.vehicle')),
            ],
        ),
    ]
