# Generated by Django 4.2.5 on 2023-09-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='vehicle_fk',
            new_name='vehicleFk',
        ),
    ]
