# Generated by Django 4.2.5 on 2023-09-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0002_rename_vehicle_fk_images_vehiclefk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(blank=True, default='images/inventory/default.jpg', upload_to='images/inventory/'),
        ),
    ]
