# Generated by Django 4.2.5 on 2023-09-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0007_alter_images_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(default='settings.MEDIA_ROOT/images/inventory/default.jpg', upload_to='images/inventory/'),
        ),
    ]
