# Generated by Django 4.2.5 on 2023-09-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0010_alter_images_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(default='myProject\\media\\images\\inventory\\default.jpg', upload_to='images/inventory/'),
        ),
    ]
