# Generated by Django 4.2.5 on 2023-09-29 12:30

from django.db import migrations, models
import frontapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0013_alter_images_filename_alter_images_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(default=frontapp.models.default_image, upload_to='images/inventory/'),
        ),
    ]
