# Generated by Django 4.2.5 on 2023-09-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0014_alter_images_filename_alter_images_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='filename',
            field=models.CharField(blank=True, default='default.jpg', max_length=100, null=True),
        ),
    ]
