# Generated by Django 4.2.5 on 2023-10-03 14:34

from django.db import migrations, models
import frontapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0015_alter_images_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image_upload',
            field=models.ImageField(default=frontapp.models.default_post_image, null=True, upload_to='images/other/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
