# Generated by Django 4.2.5 on 2023-10-03 14:37

from django.db import migrations, models
import frontapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0016_remove_post_image_post_image_upload_post_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_upload',
            field=models.ImageField(blank=True, default=frontapp.models.default_post_image, null=True, upload_to='images/other/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
