# Generated by Django 4.2.5 on 2023-10-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0017_alter_post_image_upload_alter_post_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='@UsaVehicleImports', max_length=100),
        ),
    ]
