# Generated by Django 4.2.5 on 2023-10-03 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0019_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['', 'MOV', 'avi', 'gif', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
