# Generated by Django 4.2.5 on 2023-10-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0020_alter_vehicle_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('quote', models.TextField()),
                ('rate', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
