# Generated by Django 4.2.5 on 2023-10-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0023_businessdetails_address_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='facebook',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='instagram',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='linkedIn',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='twitter',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
