# Generated by Django 4.2.5 on 2023-10-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0024_businessdetails_facebook_businessdetails_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='linkedIn',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
