# Generated by Django 4.2.5 on 2023-10-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0025_alter_businessdetails_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='google_map_link',
            field=models.URLField(blank=True),
        ),
    ]
