# Generated by Django 4.2.5 on 2023-10-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0026_businessdetails_google_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='google_map_link',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
