# Generated by Django 4.2.5 on 2023-10-11 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0027_alter_businessdetails_google_map_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalenquiry',
            old_name='from_email',
            new_name='email',
        ),
    ]
