# Generated by Django 4.2.5 on 2023-10-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0030_alter_businessdetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_taster',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
