# Generated by Django 4.2.5 on 2023-10-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0032_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
