# Generated by Django 4.2.5 on 2023-10-19 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0033_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
    ]
