# Generated by Django 4.2.5 on 2023-10-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0034_rename_like_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
