# Generated by Django 4.2.5 on 2023-11-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0038_generalenquiry_replied'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalenquiry',
            name='replied_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
