# Generated by Django 4.2.5 on 2023-11-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0041_editablestaticcontent_escparagraph_escimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editablestaticcontent',
            name='badge',
            field=models.ImageField(blank=True, height_field=50, upload_to='images/editableContent/', width_field=50),
        ),
        migrations.AlterField(
            model_name='editablestaticcontent',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='escimage',
            name='images',
            field=models.ImageField(blank=True, upload_to='images/editableContent/'),
        ),
        migrations.AlterField(
            model_name='escparagraph',
            name='paragraph',
            field=models.TextField(blank=True),
        ),
    ]
