# Generated by Django 4.2.5 on 2023-11-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0042_alter_editablestaticcontent_badge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editablestaticcontent',
            name='badge',
            field=models.ImageField(blank=True, upload_to='images/editableContent/'),
        ),
    ]
