# Generated by Django 4.2.5 on 2023-11-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0043_alter_editablestaticcontent_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavHTMLPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Home', 'Home'), ('Page2', 'Page2'), ('Page3', 'Page3'), ('Page4', 'Page4'), ('Page5', 'Page5')], max_length=100)),
                ('fontAwesomeIcon', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('imageIcon', models.ImageField(blank=True, upload_to='images/editableContent/')),
            ],
            options={
                'verbose_name_plural': 'NavHTMLPage',
            },
        ),
    ]
