# Generated by Django 4.2.5 on 2023-11-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0044_navhtmlpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navhtmlpage',
            old_name='title',
            new_name='page',
        ),
        migrations.AddField(
            model_name='navhtmlpage',
            name='header',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
