# Generated by Django 4.2.5 on 2023-11-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0045_rename_title_navhtmlpage_page_navhtmlpage_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='navhtmlpage',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
