# Generated by Django 4.2.5 on 2023-11-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0047_rename_header_navhtmlpage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalenquiry',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
