# Generated by Django 4.2.5 on 2023-11-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0048_generalenquiry_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navhtmlpage',
            name='page',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Services', 'Services'), ('Gallery', 'Gallery'), ('News', 'News')], max_length=100),
        ),
    ]
