# Generated by Django 4.2.5 on 2023-11-12 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0049_alter_navhtmlpage_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editablestaticcontent',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='navhtmlpage',
            name='slug',
        ),
    ]
